@startuml
!include ../../plantuml/sodexo-theme.puml

title Reject a Request
header Sat, 25 Jul 2026 at 12:44:28 PM


(*) -right-> "Select a rejection\ncategory and reason"
-right-> "Reject the request"
-right-> "Notify the traveller\nof the decision" #DDF2E9
-right-> (*)

@enduml
