@startuml
!include ../../plantuml/sodexo-theme.puml

title Manage the Booking Work Queue
header Sat, 25 Jul 2026 at 12:46:58 PM


(*) -right-> "Open requests awaiting\nbooking or exception handling"
-right-> "Filter and prioritise\nby travel date and risk"
-right-> "Claim a request"
-right-> "Open the complete\nrequest history" #DDF2E9
-right-> (*)

@enduml
