@startuml
!include ../../plantuml/sodexo-theme.puml

title Manage Price Ranges and Exceptions
header Sat, 25 Jul 2026 at 12:45:58 PM


(*) -right-> "Select a role level,\ndestination and period"
-right-> "Define the permitted\nnightly range"
-right-> "Configure warning, hard-stop\nand exception rules"
-right-> "Publish the versioned\nprice rule" #DDF2E9
-right-> (*)

@enduml
