@startuml
!include ../../plantuml/sodexo-theme.puml

title Traveller Journey 1 · Select Accommodation
footer (c) Developed by <b>Mohit Kanwar</b>

(*) -right-> "Log in through the\nexisting Sodexo B2C application"
-right-> "Search for available\naccommodation"
-right-> "Select an option"
-right-> "Submit for approval" #DDF2E9
-right-> (*)

@enduml
