@startuml
!include ../../plantuml/sodexo-theme.puml

title Traveller Journey 4 · View Requests
footer (c) Developed by <b>Mohit Kanwar</b>

(*) -right-> "Open my requests"
-right-> "View the list of\nsubmitted requests"
-right-> "Select a request"
-right-> "View request status\nand details" #DDF2E9
-right-> (*)

@enduml
