// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  documentationSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
