// @ts-check

const {readFileSync} = require('node:fs');
const path = require('node:path');

/**
 * Embeds the SVG generated by scripts/generate-plantuml.mjs at a
 * `plantuml-image` fenced-block placeholder.
 *
 * Example:
 *   ```plantuml-image
 *   ./api-flow.puml | Booking API flow
 *   ```
 */
module.exports = function plantumlImages() {
  return (tree, file) => {
    visit(tree, file);
  };
};

function visit(node, file) {
  if (!node || typeof node !== 'object') {
    return;
  }

  if (
    node.type === 'code' &&
    node.lang === 'plantuml-image' &&
    typeof node.value === 'string'
  ) {
    const match = node.value.trim().match(
      /^([^|\s]+\.puml)(?:\s*\|\s*([\s\S]*?))?$/i,
    );

    if (match) {
      const markdownPath = file.path;
      if (!markdownPath) {
        throw new Error('PlantUML placeholder has no Markdown file path.');
      }

      const sourceReference = match[1];
      const alt = (match[2] || path.basename(sourceReference, '.puml')).trim();
      const svgPath = path.resolve(
        path.dirname(markdownPath),
        `${sourceReference}.svg`,
      );
      const svg = readFileSync(svgPath);

      node.type = 'image';
      node.url = `data:image/svg+xml;base64,${svg.toString('base64')}`;
      node.alt = alt;
      node.title = null;
      delete node.lang;
      delete node.meta;
      delete node.value;
    } else {
      throw new Error(
        'PlantUML placeholder must contain "./diagram.puml | Alternative text".',
      );
    }
  }

  if (Array.isArray(node.children)) {
    node.children.forEach((child) => visit(child, file));
  }
}
