// @ts-check

const path = require('node:path');

/**
 * Embeds the SVG generated by scripts/generate-plantuml.mjs at a
 * `plantuml-image` fenced-block placeholder.
 *
 * Example:
 *   ```plantuml-image
 *   ./diagrams/api-flow/api-flow.puml | Booking API flow
 *   ```
 */
module.exports = function plantumlImages({baseUrl = '/'} = {}) {
  return (tree, file) => {
    visit(tree, file, baseUrl);
  };
};

function visit(node, file, baseUrl) {
  if (!node || typeof node !== 'object') {
    return;
  }

  if (
    node.type === 'code' &&
    node.lang === 'plantuml-image' &&
    typeof node.value === 'string'
  ) {
    const match = node.value.trim().match(
      /^([^|\s]+\.puml)(?:\s*\|\s*([\s\S]*?))?$/i,
    );

    if (match) {
      const markdownPath = file.path;
      if (!markdownPath) {
        throw new Error('PlantUML placeholder has no Markdown file path.');
      }

      const sourceReference = match[1];
      const alt = (match[2] || path.basename(sourceReference, '.puml')).trim();
      const sourcePath = path.resolve(
        path.dirname(markdownPath),
        sourceReference,
      );
      const docsMarker = `${path.sep}docs${path.sep}`;
      const docsIndex = sourcePath.lastIndexOf(docsMarker);
      if (docsIndex === -1) {
        throw new Error(`PlantUML source is outside docs/: ${sourceReference}`);
      }

      const docsRelativePath = sourcePath
        .slice(docsIndex + docsMarker.length)
        .split(path.sep)
        .join('/');
      const normalizedBaseUrl = `/${baseUrl}/`.replace(/\/+/g, '/');

      node.type = 'image';
      node.url =
        `${normalizedBaseUrl}plantuml/${docsRelativePath}.svg`;
      node.alt = alt;
      node.title = null;
      delete node.lang;
      delete node.meta;
      delete node.value;
    } else {
      throw new Error(
        'PlantUML placeholder must contain "./diagram.puml | Alternative text".',
      );
    }
  }

  if (Array.isArray(node.children)) {
    node.children.forEach((child) => visit(child, file, baseUrl));
  }
}
