@startuml
!include plantuml/sodexo-theme.puml

title Raise a Booking Issue
header Sat, 25 Jul 2026 at 11:05:42 AM


(*) -right-> "Open a booking"
-right-> "Select raise an issue"
-right-> "Describe the issue"
-right-> "Submit the issue to support" #DDF2E9
-right-> (*)

@enduml
