@startuml
!include plantuml/sodexo-theme.puml

title Download or Email the Confirmation Letter
header Sat, 25 Jul 2026 at 11:05:04 AM


(*) -right-> "Open a confirmed booking"
if "Download or\nemail?" then
  --> [download] "Download the confirmation letter" #DDF2E9
  --> (*)
else
  --> [email] "Email the confirmation letter" #DDF2E9
  --> (*)
endif

@enduml
