@startuml
!include plantuml/sodexo-theme.puml

title Cancel a Submitted Request
header Sat, 25 Jul 2026 at 11:04:19 AM


(*) -right-> "Open an existing request"
-right-> "Select cancel request"
-right-> "Confirm the cancellation"
-right-> "Request marked as cancelled" #DDF2E9
-right-> (*)

@enduml
