@startuml
!include plantuml/sodexo-theme.puml

title Follow Up on an Unapproved Request
header Sat, 25 Jul 2026 at 11:04:52 AM


(*) -right-> "Open a pending request"
-right-> "Send a follow-up reminder"
-right-> "Approver is notified" #DDF2E9
-right-> (*)

@enduml
