@startuml
!include plantuml/sodexo-theme.puml

title View Accommodation Contact Details
header Sat, 25 Jul 2026 at 11:05:25 AM



(*) -right-> "Open a confirmed booking"
-right-> "View accommodation\ncontact details" #DDF2E9
-right-> (*)

@enduml
