@startuml
!include plantuml/sodexo-theme.puml

title View Requests
header Sat, 25 Jul 2026 at 11:04:39 AM


(*) -right-> "Open my requests"
-right-> "View the list of\nsubmitted requests"
-right-> "Select a request"
-right-> "View request status\nand details" #DDF2E9
-right-> (*)

@enduml
