@startuml
!include plantuml/sodexo-theme.puml

title Select Accommodation
header Sat, 25 Jul 2026 at 11:03:52 AM


(*) -right-> "Log in through the\nexisting Sodexo B2C application"
-right-> "Search for available\naccommodation"
-right-> "Select an option"
-right-> "Submit for approval" #DDF2E9
-right-> (*)

@enduml
